[package]
name = "uial-geometry"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1", features = ["full"] }
thiserror = "2"
approx = "0.5"
num-rational = { version = "0.4", default-features = false }
bytemuck = { version = "1", features = ["derive"] }
