[package]
name = "uial-geometry"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["full"] }
thiserror = "1.0.63"
approx = "0.5.1"
num-rational = { version = "0.4.2", default-features = false }
bytemuck = { version = "1.17.0", features = ["derive"] }
