[package]
name = "uial"
version = "0.1.0"
edition = "2021"

[dependencies]
uial-geometry = { path = "../geometry" }
renege = "0.1.1"
derive_more = "0.99.17"
winit = "0.28.3"
palette = "0.7.1"
image = "0.24.6"
guillotiere = "0.6.2"
ttf-parser = "0.19.0"
ab_glyph_rasterizer = "0.1.8"
ghost-cell = "0.2.3"
rand = "0.8.5"
num-rational = { version = "0.4.1", default-features = false }

[dev-dependencies]
uial-backend = { path = "../backend" }
approx = "0.5.1"